#!/usr/bin/env bash
# This script groups IPs and HTTP codes with occurrence counts, sorted descending

awk '
{
  count[$1" "$9]++
}
END {
  for (key in count) {
    print count[key], key
  }
}
' apache-access.log | sort -rn

